version: '3'
services:
  api:
    image: aaronmwilliams/user-exercises-rest
    ports:
      - 8080:8080
  tests:
    image: aaronmwilliams/user-exercises-rest
    entrypoint: mvn test "-Dtest=*UnitTest.java"
